# prod profile — 生产环境时激活

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false    # 关掉 UI 页面


logging:
  level:
    com.murasame: WARN

security:
  cookie:
    secure: true

jwt:
  access-token-expiration: 1800000     # 30 分钟
