server:
  port: 8080

spring:
  application:
    name: myBlog

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/myblog
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      username:
      password:

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.qq.com
    port: 587
    username:
    password:

mybatis:
  configuration:
    map-underscore-to-camel-case: true

weather:
  seniverse:
    uid:
    key:
    sign-enabled: false

github:
  token:

tencent:
  cos:
    secret-id:
    secret-key:
    region: ap-guangzhou
    bucket-name:
    base-url:
    folder: blog/images

jwt:
  secret:
  access-token-expiration: 1800000
  refresh-token-expiration: 604800000
